meta_product_name: "Poubelles Battle"
meta_title: "Poubelles Battle - Compostez vos dechets alimentaires à Pau"
meta_description: "Un composteur pour tou•te•s ! Que vous habitiez en maison individuelle, en appartement sans jardin, en résidence, il existe une solution pour chacun•e ! Découvrez les composteurs collectifs mis à disposition à Pau et l'agglomération."
meta_image: "cover.png" # should exist in `app/assets/images/`
